# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeReadout < Formula
  desc "Terminal-aware status line for Claude Code"
  homepage "https://github.com/SteveVitali/claude-readout"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/SteveVitali/claude-readout/releases/download/v0.1.0/claude-readout_0.1.0_darwin_amd64.tar.gz"
      sha256 "736adb9d72d2d0337309f2c81006b86d141adb2f853aa0eaebb02fd9c1c32223"

      define_method(:install) do
        bin.install "claude-readout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/SteveVitali/claude-readout/releases/download/v0.1.0/claude-readout_0.1.0_darwin_arm64.tar.gz"
      sha256 "361546e64a738f6ebfaa1402659e20e7bff8baad095717822d1613bff1b3e648"

      define_method(:install) do
        bin.install "claude-readout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/SteveVitali/claude-readout/releases/download/v0.1.0/claude-readout_0.1.0_linux_amd64.tar.gz"
      sha256 "8195121c63fc5bc7d2d1e5c516e936894f1be14e07db3cc0367b3f174dba1176"
      define_method(:install) do
        bin.install "claude-readout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/SteveVitali/claude-readout/releases/download/v0.1.0/claude-readout_0.1.0_linux_arm64.tar.gz"
      sha256 "512d58a6b35e23ed593b7169fb8694c9b9a56c80f230466a28be71294031307d"
      define_method(:install) do
        bin.install "claude-readout"
      end
    end
  end

  test do
    system "#{bin}/claude-readout", "version"
  end
end
